import { useMemo, useState, type ReactElement } from 'react';
import {
  FileBarChart,
  Clock,
  MessageSquare,
  Hash,
  Sparkles,
  Send,
  Settings as SettingsIcon,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Zap,
} from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { PageSpinner } from '../components/ui/Spinner';
import { EmptyState } from '../components/ui/EmptyState';
import { Modal } from '../components/ui/Modal';
import { useMachines } from '../hooks/useMachines';
import { useAllAgents } from '../hooks/useAgents';
import {
  useSummariesList,
  useSummaryStatus,
  useSummaryDetail,
  useSummaryPushConfig,
  useSetSummaryPushEnabled,
  useGenerateSummary,
} from '../hooks/useSummaries';
import type {
  SessionSummary,
  SummaryStatus,
  SummaryTrigger,
  GenerateSummaryResult,
} from '../api/summaries.api';

const STATUS_VARIANT: Record<SummaryStatus, 'success' | 'warning' | 'danger' | 'muted'> = {
  success: 'success',
  empty: 'muted',
  failed: 'danger',
};

const STATUS_LABEL: Record<SummaryStatus, string> = {
  success: '已生成',
  empty: '空窗口',
  failed: '失败',
};

const TRIGGER_LABEL: Record<SummaryTrigger, string> = {
  scheduled: '定时',
  manual: '手动',
};

function formatTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function formatDateTime(iso: string | null | undefined): string {
  if (!iso) return '-';
  const d = new Date(iso);
  return `${d.toLocaleDateString()} ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
}

function formatWindow(start: string, end: string): string {
  const s = new Date(start);
  const e = new Date(end);
  const sameDay = s.toDateString() === e.toDateString();
  const fmt = (d: Date) =>
    `${d.toLocaleDateString()} ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  return sameDay
    ? `${fmt(s)} ~ ${e.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`
    : `${fmt(s)} ~ ${fmt(e)}`;
}

// ─── Lightweight markdown renderer ───────────────────────────────────
// The summary markdown is generated by Gemini with a consistent section
// style (# / ## / ### / - list / **bold**). We render a styled HTML-ish
// view instead of pulling in `react-markdown` because the dep isn't in
// the project yet; this keeps the bundle small and visually matches the
// rest of the console.
function SummaryMarkdown({ text }: { text: string }) {
  const elements: ReactElement[] = [];
  const lines = text.split('\n');
  let listBuffer: string[] = [];

  const flushList = () => {
    if (listBuffer.length === 0) return;
    elements.push(
      <ul key={`ul-${elements.length}`} className="list-disc pl-5 space-y-0.5 text-sm text-claw-text">
        {listBuffer.map((item, i) => (
          <li key={i} dangerouslySetInnerHTML={{ __html: renderInline(item) }} />
        ))}
      </ul>,
    );
    listBuffer = [];
  };

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (/^###\s+/.test(line)) {
      flushList();
      elements.push(
        <h3 key={elements.length} className="text-sm font-semibold text-claw-primary-light mt-4 mb-1">
          {line.replace(/^###\s+/, '')}
        </h3>,
      );
    } else if (/^##\s+/.test(line)) {
      flushList();
      elements.push(
        <h2 key={elements.length} className="text-base font-bold text-claw-text mt-5 mb-2 border-b border-claw-border pb-1">
          {line.replace(/^##\s+/, '')}
        </h2>,
      );
    } else if (/^#\s+/.test(line)) {
      flushList();
      elements.push(
        <h1 key={elements.length} className="text-lg font-bold text-claw-text mt-2 mb-3">
          {line.replace(/^#\s+/, '')}
        </h1>,
      );
    } else if (/^\s*[-*]\s+/.test(line)) {
      listBuffer.push(line.replace(/^\s*[-*]\s+/, ''));
    } else if (line.trim() === '') {
      flushList();
    } else if (/^---+$/.test(line.trim())) {
      flushList();
      elements.push(<hr key={elements.length} className="my-3 border-claw-border" />);
    } else {
      flushList();
      elements.push(
        <p
          key={elements.length}
          className="text-sm text-claw-text leading-relaxed my-1.5"
          dangerouslySetInnerHTML={{ __html: renderInline(line) }}
        />,
      );
    }
  }
  flushList();

  return <div className="prose-sm">{elements}</div>;
}

function renderInline(s: string): string {
  // Escape then apply minimal styling (bold, italic, inline code).
  const escaped = s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  return escaped
    .replace(/`([^`]+)`/g, '<code class="px-1 py-0.5 rounded bg-claw-bg text-claw-primary-light text-xs">$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong class="text-claw-text">$1</strong>')
    .replace(/__([^_]+)__/g, '<strong class="text-claw-text">$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>');
}

// ─── Detail panel ───────────────────────────────────────────────────

function SummaryDetailPanel({
  summaryId,
  onClose,
}: {
  summaryId: number;
  onClose: () => void;
}) {
  const { data, isLoading } = useSummaryDetail(summaryId);

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex justify-end">
      <div className="w-full max-w-3xl bg-claw-bg border-l border-claw-border flex flex-col">
        <div className="p-4 border-b border-claw-border flex items-start justify-between">
          <div>
            <h3 className="text-sm font-semibold text-claw-text">会话总结详情</h3>
            {data && (
              <div className="text-xs text-claw-muted mt-1">
                {formatWindow(data.periodStartAt, data.periodEndAt)}
              </div>
            )}
          </div>
          <button
            onClick={onClose}
            className="text-claw-muted hover:text-claw-text text-lg cursor-pointer"
          >
            &times;
          </button>
        </div>

        {isLoading || !data ? (
          <div className="flex-1 flex items-center justify-center">
            <PageSpinner />
          </div>
        ) : (
          <>
            <div className="px-4 py-3 border-b border-claw-border grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">
              <MetaCell label="Bot" value={data.agentId} />
              <MetaCell label="会话数" value={String(data.sessionCount)} />
              <MetaCell label="消息数" value={String(data.messageCount)} />
              <MetaCell label="Token" value={formatTokens(data.totalTokens)} />
              <MetaCell label="触发" value={TRIGGER_LABEL[data.trigger]} />
              <MetaCell label="状态" value={STATUS_LABEL[data.status]} />
              <MetaCell label="模型" value={data.model ?? '-'} />
              <MetaCell
                label="飞书推送"
                value={
                  data.feishuPushed ? '已推送' : data.feishuPushError ? '失败' : '未推送'
                }
              />
            </div>
            {data.feishuPushError && (
              <div className="px-4 py-2 border-b border-claw-border bg-claw-danger/10 text-xs text-claw-danger flex items-start gap-2">
                <AlertTriangle size={14} className="mt-0.5 shrink-0" />
                <span>飞书推送失败：{data.feishuPushError}</span>
              </div>
            )}
            {data.errorMessage && (
              <div className="px-4 py-2 border-b border-claw-border bg-claw-danger/10 text-xs text-claw-danger flex items-start gap-2">
                <AlertTriangle size={14} className="mt-0.5 shrink-0" />
                <span>生成失败：{data.errorMessage}</span>
              </div>
            )}
            <div className="flex-1 overflow-y-auto p-5">
              {data.summaryMarkdown ? (
                <SummaryMarkdown text={data.summaryMarkdown} />
              ) : (
                <div className="text-center text-claw-muted text-sm py-8">
                  {data.status === 'empty'
                    ? '该时间窗口内没有会话消息，无内容可总结。'
                    : '暂无总结内容'}
                </div>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function MetaCell({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-claw-muted text-[10px] uppercase tracking-wide">{label}</div>
      <div className="text-claw-text mt-0.5">{value}</div>
    </div>
  );
}

// ─── Generate dialog ─────────────────────────────────────────────────

function GenerateModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { data: agentsData } = useAllAgents();
  const agents = agentsData?.data ?? [];
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [days, setDays] = useState(1);
  const [forcePush, setForcePush] = useState(true);
  const [results, setResults] = useState<GenerateSummaryResult[] | null>(null);
  const generate = useGenerateSummary();

  const toggle = (uuid: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(uuid)) next.delete(uuid);
      else next.add(uuid);
      return next;
    });
  };

  const toggleAll = () => {
    if (selected.size === agents.length) setSelected(new Set());
    else setSelected(new Set(agents.map((a) => a.id)));
  };

  const submit = async () => {
    if (selected.size === 0) return;
    setResults(null);
    const resp = await generate.mutateAsync({
      agentUuids: Array.from(selected),
      days,
      forcePush,
    });
    setResults(resp.results);
  };

  const reset = () => {
    setSelected(new Set());
    setDays(1);
    setForcePush(true);
    setResults(null);
    onClose();
  };

  return (
    <Modal open={open} onClose={reset} title="立即生成会话总结" width="max-w-2xl">
      {!results ? (
        <div className="space-y-4">
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm text-claw-text font-medium">选择 Bot</label>
              <button
                type="button"
                onClick={toggleAll}
                className="text-xs text-claw-primary-light hover:underline cursor-pointer"
              >
                {selected.size === agents.length ? '全不选' : '全选'}
              </button>
            </div>
            <div className="max-h-56 overflow-y-auto border border-claw-border rounded-lg">
              {agents.length === 0 ? (
                <div className="p-4 text-center text-xs text-claw-muted">
                  没有可用的 Bot
                </div>
              ) : (
                agents.map((a) => (
                  <label
                    key={a.id}
                    className="flex items-center gap-2 px-3 py-2 border-b border-claw-border last:border-b-0 hover:bg-claw-card cursor-pointer"
                  >
                    <input
                      type="checkbox"
                      checked={selected.has(a.id)}
                      onChange={() => toggle(a.id)}
                    />
                    <div className="flex-1 min-w-0">
                      <div className="text-sm text-claw-text truncate">
                        {a.name || a.agentId}
                      </div>
                      <div className="text-xs text-claw-muted truncate">
                        {a.machineName} · {a.agentId}
                      </div>
                    </div>
                  </label>
                ))
              )}
            </div>
            <div className="text-xs text-claw-muted mt-1">
              已选 {selected.size} 个
            </div>
          </div>

          <div>
            <label className="text-sm text-claw-text font-medium block mb-2">
              回溯天数
            </label>
            <div className="flex items-center gap-2">
              <select
                value={days}
                onChange={(e) => setDays(Number(e.target.value))}
                className="bg-claw-card border border-claw-border rounded-lg px-3 py-1.5 text-sm text-claw-text"
              >
                <option value={1}>最近 1 天</option>
                <option value={2}>最近 2 天</option>
                <option value={3}>最近 3 天</option>
                <option value={7}>最近 7 天</option>
                <option value={14}>最近 14 天</option>
              </select>
              <span className="text-xs text-claw-muted">
                范围：今天回溯 {days} 天内的所有会话
              </span>
            </div>
          </div>

          <label className="flex items-start gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={forcePush}
              onChange={(e) => setForcePush(e.target.checked)}
              className="mt-1"
            />
            <div>
              <div className="text-sm text-claw-text">生成后推送到飞书</div>
              <div className="text-xs text-claw-muted">
                勾选后，成功生成的总结会发送到配置的飞书群；忽略 bot 的定时推送开关
              </div>
            </div>
          </label>

          <div className="flex justify-end gap-2 pt-2">
            <Button variant="secondary" onClick={reset}>
              取消
            </Button>
            <Button
              onClick={submit}
              loading={generate.isPending}
              disabled={selected.size === 0 || generate.isPending}
              icon={<Sparkles size={14} />}
            >
              开始生成
            </Button>
          </div>
        </div>
      ) : (
        <div className="space-y-3">
          <div className="text-sm text-claw-text">
            已处理 {results.length} 个 Bot：
          </div>
          <div className="max-h-80 overflow-y-auto space-y-1.5">
            {results.map((r, idx) => (
              <div
                key={idx}
                className="flex items-start gap-2 px-3 py-2 border border-claw-border rounded-lg"
              >
                {r.status === 'success' ? (
                  <CheckCircle2 size={16} className="text-claw-success mt-0.5 shrink-0" />
                ) : r.status === 'empty' ? (
                  <AlertTriangle size={16} className="text-claw-muted mt-0.5 shrink-0" />
                ) : (
                  <XCircle size={16} className="text-claw-danger mt-0.5 shrink-0" />
                )}
                <div className="flex-1 min-w-0">
                  <div className="text-sm text-claw-text">{r.agentId}</div>
                  <div className="text-xs text-claw-muted mt-0.5">
                    {r.status === 'success'
                      ? `${r.sessionCount} 会话 / ${r.messageCount} 消息${r.pushed ? ' · 已推送飞书' : r.pushError ? ` · 飞书失败: ${r.pushError}` : ''}`
                      : r.status === 'empty'
                        ? '该时间窗口无消息'
                        : r.errorMessage ?? '生成失败'}
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div className="flex justify-end gap-2 pt-2">
            <Button onClick={reset}>完成</Button>
          </div>
        </div>
      )}
    </Modal>
  );
}

// ─── Push config dialog ──────────────────────────────────────────────

function PushConfigModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { data: configs, isLoading } = useSummaryPushConfig();
  const setEnabled = useSetSummaryPushEnabled();

  return (
    <Modal open={open} onClose={onClose} title="定时推送设置" width="max-w-xl">
      <div className="space-y-3">
        <div className="text-xs text-claw-muted">
          勾选的 Bot 会在每日 00:00 / 12:00 的定时总结完成后自动推送到飞书群。
          手动生成时可以在对话框里勾选「生成后推送」强制推送。
        </div>
        {isLoading ? (
          <PageSpinner />
        ) : !configs || configs.length === 0 ? (
          <EmptyState title="暂无 Bot" description="请先创建 Bot" />
        ) : (
          <div className="max-h-96 overflow-y-auto border border-claw-border rounded-lg">
            {configs.map((c) => (
              <div
                key={c.agentUuid}
                className="flex items-center gap-3 px-3 py-2.5 border-b border-claw-border last:border-b-0"
              >
                <div className="flex-1 min-w-0">
                  <div className="text-sm text-claw-text truncate">
                    {c.agentName || c.agentId}
                  </div>
                  <div className="text-xs text-claw-muted truncate">
                    {c.machineName} · {c.agentId}
                  </div>
                </div>
                <label className="inline-flex items-center cursor-pointer">
                  <input
                    type="checkbox"
                    checked={c.enabled}
                    disabled={setEnabled.isPending}
                    onChange={(e) =>
                      setEnabled.mutate({
                        agentUuid: c.agentUuid,
                        enabled: e.target.checked,
                      })
                    }
                    className="sr-only peer"
                  />
                  <div className="w-9 h-5 bg-claw-border rounded-full peer-checked:bg-claw-primary relative transition-colors">
                    <div
                      className={`absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full transition-transform ${
                        c.enabled ? 'translate-x-4' : ''
                      }`}
                    />
                  </div>
                </label>
              </div>
            ))}
          </div>
        )}
      </div>
    </Modal>
  );
}

// ─── Main page ───────────────────────────────────────────────────────

export function SummariesPage() {
  const [machineId, setMachineId] = useState('');
  const [agentId, setAgentId] = useState('');
  const [trigger, setTrigger] = useState<'' | SummaryTrigger>('');
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [showGenerate, setShowGenerate] = useState(false);
  const [showPushConfig, setShowPushConfig] = useState(false);

  const { data: status } = useSummaryStatus();
  const { data: machinesData } = useMachines();
  const { data: agentsData } = useAllAgents();
  const { data, isLoading } = useSummariesList({
    machineId: machineId || undefined,
    agentId: agentId || undefined,
    trigger: trigger || undefined,
    limit: 100,
  });

  const machines = machinesData?.data ?? [];
  const agents = agentsData?.data ?? [];
  const summaries = data?.data ?? [];

  // Filter agents by currently-selected machine so the "Bot" dropdown
  // shows only relevant options; this matches the pattern used in the
  // sessions page.
  const agentOptions = useMemo(() => {
    const filtered = machineId
      ? agents.filter((a) => a.machineId === machineId)
      : agents;
    return [...new Set(filtered.map((a) => a.agentId))].sort();
  }, [agents, machineId]);

  const geminiMissing = status && !status.geminiConfigured;
  const feishuMissing = status && !status.feishuConfigured;

  return (
    <div>
      <div className="flex items-center justify-between mb-5 gap-3 flex-wrap">
        <div>
          <h1 className="text-lg font-bold text-claw-text flex items-center gap-2">
            <FileBarChart size={20} className="text-claw-primary-light" />
            会话总结
          </h1>
          {status && (
            <div className="text-xs text-claw-muted mt-1">
              每 {status.windowHours}h 自动生成 · 模型 {status.model}
            </div>
          )}
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="secondary"
            onClick={() => setShowPushConfig(true)}
            icon={<SettingsIcon size={14} />}
          >
            推送设置
          </Button>
          <Button
            onClick={() => setShowGenerate(true)}
            icon={<Sparkles size={14} />}
            disabled={!!geminiMissing}
          >
            立即生成
          </Button>
        </div>
      </div>

      {geminiMissing && (
        <Card className="mb-4 !border-claw-danger/40 bg-claw-danger/10">
          <div className="flex items-start gap-2 text-sm text-claw-danger">
            <AlertTriangle size={16} className="mt-0.5 shrink-0" />
            <div>
              <div className="font-medium">未配置 Gemini API Key</div>
              <div className="text-xs mt-0.5 text-claw-danger/80">
                请在 backend 的 .env 设置 <code className="font-mono">GEMINI_API_KEY</code>
                后重启服务，定时总结和手动生成才会执行。
              </div>
            </div>
          </div>
        </Card>
      )}

      {feishuMissing && !geminiMissing && (
        <Card className="mb-4 !border-claw-warning/40 bg-claw-warning/10">
          <div className="flex items-start gap-2 text-sm text-claw-warning">
            <AlertTriangle size={16} className="mt-0.5 shrink-0" />
            <div>
              <div className="font-medium">飞书推送未配置</div>
              <div className="text-xs mt-0.5 text-claw-warning/80">
                总结仍会生成并入库，但无法发送到飞书群。
                {status?.feishuHint ? ` ${status.feishuHint}` : ''}
              </div>
            </div>
          </div>
        </Card>
      )}

      <div className="flex items-center gap-3 mb-4 flex-wrap">
        <select
          value={machineId}
          onChange={(e) => {
            setMachineId(e.target.value);
            setAgentId('');
          }}
          className="bg-claw-card border border-claw-border rounded-lg px-3 py-1.5 text-sm text-claw-text"
        >
          <option value="">全部节点</option>
          {machines.map((m) => (
            <option key={m.id} value={m.id}>
              {m.name}
            </option>
          ))}
        </select>

        <select
          value={agentId}
          onChange={(e) => setAgentId(e.target.value)}
          className="bg-claw-card border border-claw-border rounded-lg px-3 py-1.5 text-sm text-claw-text"
        >
          <option value="">全部 Bot</option>
          {agentOptions.map((a) => (
            <option key={a} value={a}>
              {a}
            </option>
          ))}
        </select>

        <select
          value={trigger}
          onChange={(e) => setTrigger(e.target.value as '' | SummaryTrigger)}
          className="bg-claw-card border border-claw-border rounded-lg px-3 py-1.5 text-sm text-claw-text"
        >
          <option value="">全部触发</option>
          <option value="scheduled">定时</option>
          <option value="manual">手动</option>
        </select>

        <div className="ml-auto text-xs text-claw-muted">
          共 {data?.total ?? 0} 条记录
        </div>
      </div>

      {isLoading ? (
        <PageSpinner />
      ) : summaries.length === 0 ? (
        <EmptyState
          title="暂无会话总结"
          description="定时任务会在每日 00:00 / 12:00 自动生成；也可以点右上角「立即生成」"
        />
      ) : (
        <div className="space-y-2">
          {summaries.map((s) => (
            <SummaryRow
              key={s.id}
              summary={s}
              onClick={() => setSelectedId(s.id)}
            />
          ))}
        </div>
      )}

      {selectedId != null && (
        <SummaryDetailPanel
          summaryId={selectedId}
          onClose={() => setSelectedId(null)}
        />
      )}

      <GenerateModal open={showGenerate} onClose={() => setShowGenerate(false)} />
      <PushConfigModal open={showPushConfig} onClose={() => setShowPushConfig(false)} />
    </div>
  );
}

function SummaryRow({
  summary,
  onClick,
}: {
  summary: SessionSummary;
  onClick: () => void;
}) {
  return (
    <Card hover onClick={onClick} padding="p-4">
      <div className="flex items-start justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-sm font-medium text-claw-text">
              {summary.agentId}
            </span>
            <Badge variant="info">{TRIGGER_LABEL[summary.trigger]}</Badge>
            <Badge variant={STATUS_VARIANT[summary.status]}>
              {STATUS_LABEL[summary.status]}
            </Badge>
            {summary.feishuPushed && (
              <Badge variant="success">
                <Send size={10} className="inline mr-1" />
                已推送
              </Badge>
            )}
            {summary.feishuPushError && (
              <Badge variant="danger">推送失败</Badge>
            )}
          </div>
          <div className="flex items-center gap-4 mt-1.5 text-xs text-claw-muted flex-wrap">
            <span className="flex items-center gap-1">
              <Clock size={10} />
              {formatWindow(summary.periodStartAt, summary.periodEndAt)}
            </span>
            <span className="flex items-center gap-1">
              <MessageSquare size={10} />
              {summary.sessionCount} 会话
            </span>
            <span className="flex items-center gap-1">
              <Hash size={10} />
              {summary.messageCount} 消息
            </span>
            <span className="flex items-center gap-1">
              <Zap size={10} />
              {formatTokens(summary.totalTokens)} tok
            </span>
          </div>
        </div>
        <div className="text-right shrink-0 text-xs text-claw-muted">
          {formatDateTime(summary.createdAt)}
        </div>
      </div>
    </Card>
  );
}
